#include <roken.h>
#include <gssapi/gssapi_krb5.h>

gss_OID_desc *SHIM_GSS_C_NT_ANONYMOUS = NULL;
gss_OID_desc *SHIM_GSS_C_NT_EXPORT_NAME = NULL;
gss_OID_desc *SHIM_GSS_C_NT_HOSTBASED_SERVICE = NULL;
gss_OID_desc *SHIM_GSS_C_NT_HOSTBASED_SERVICE_X = NULL;
gss_OID_desc *SHIM_GSS_C_NT_MACHINE_UID_NAME = NULL;
gss_OID_desc *SHIM_GSS_C_NT_STRING_UID_NAME = NULL;
gss_OID_desc *SHIM_GSS_C_NT_USER_NAME = NULL;
gss_OID_desc *SHIM_GSS_KRB5_NT_PRINCIPAL_NAME = NULL;

void __init_gssapi_shim(void)
{
    SHIM_GSS_C_NT_ANONYMOUS = GSS_C_NT_ANONYMOUS;
    SHIM_GSS_C_NT_EXPORT_NAME = GSS_C_NT_EXPORT_NAME;
    SHIM_GSS_C_NT_HOSTBASED_SERVICE = GSS_C_NT_HOSTBASED_SERVICE;
    SHIM_GSS_C_NT_HOSTBASED_SERVICE_X = GSS_C_NT_HOSTBASED_SERVICE_X;
    SHIM_GSS_C_NT_MACHINE_UID_NAME = GSS_C_NT_MACHINE_UID_NAME;
    SHIM_GSS_C_NT_STRING_UID_NAME = GSS_C_NT_STRING_UID_NAME;
    SHIM_GSS_C_NT_USER_NAME = GSS_C_NT_USER_NAME;
    SHIM_GSS_KRB5_NT_PRINCIPAL_NAME = GSS_KRB5_NT_PRINCIPAL_NAME;
}

BOOL WINAPI DllMain(HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpvReserved)
{
    if (fdwReason == DLL_PROCESS_ATTACH) {
        __init_gssapi_shim();
    }
}
