[libdefaults]
        default_realm = EXAMPLE.COM
        rdns = false
        pkinit_anchors  = FILE:/var/heimdal/ca-pub.pem

[realms]
        EXAMPLE.COM = {
                kdc = 127.0.0.1:1088
                kpasswd_server = 127.0.0.1
        }

[kdc]
	ports = 1088
        database = {
                dbname = sqlite:/var/heimdal/heimdal.db
        }
        require-preauth = yes
        check-ticket-addresses = false
        enable-pkinit = yes
        allow-anonymous = yes
        pkinit_anchors  = FILE:/var/heimdal/ca-pub.pem
        pkinit_identity = FILE:/var/heimdal/kdc-priv.pem

        enable-kx509 = yes

[logging]
        kdc = 0-3/SYSLOG

